language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls
  - pip install .
script: 
  - python -m typeguess.guess_core
  - python -m typeguess.vcard_translator
  - nosetests --with-coverage --cover-package=typeguess
after_success:
  coveralls
