language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
install:
  - pip install coveralls
  - pip install .
script: 
  - nosetests --with-coverage --cover-package=hnapi
after_success:
  coveralls
